### ISSUE TITLE
analyze_dyncall.py causes Exception (range() result too many items)

### ISSUE THREAD

**Issue by trumeetration** [nneonneo/ghidra-wasm-plugin#22] opened 2024-07-05 14:49 UTC
Hello, i am using:

- Ghidra 11.1.1
- Il2CppDumper v.6.7.45
- Ghidra WASM Plugin 2.3.1

Issue:
I am trying to run ghidra_wasm.py from Il2CppDumper, which refers to your plugin and it calls analyze_dyncalls.py. In execution this file shows these logs and exception at the end:
ghidra_wasm.py> Running...
```
Failed to analyze export::dynCall_jiji: call_indirect not found
...
Failed to analyze export::dynCall_jiiiiiiiiii: call_indirect not found
Failed to analyze export::dynCall_jiiiiji: call_indirect not found
4294967295
Traceback (most recent call last):
  File "F:\Softs\cheats\unity\Il2CppDumper-win-v6.7.45\ghidra_wasm.py", line 11, in <module>
    runScript("analyze_dyncalls.py")
  File "C:\Users\trum\AppData\Roaming\ghidra\ghidra_11.1.1_PUBLIC\Extensions\ghidra-wasm-plugin\ghidra_scripts\analyze_dyncalls.py", line 139, in <module>
    renameDyncalls(calltype)
  File "C:\Users\trum\AppData\Roaming\ghidra\ghidra_11.1.1_PUBLIC\Extensions\ghidra-wasm-plugin\ghidra_scripts\analyze_dyncalls.py", line 111, in renameDyncalls
    for i in range(mask + 1):
OverflowError: range() result has too many items
ghidra_wasm.py> Finished!
```
The number 4294967295 before Traceback is result of print(mask).

What should i do?

**Comment by nneonneo** [comment] 2024-07-06 06:34
This is a duplicate of #14 and #18; please read those issues.

**Closed by nneonneo** 2024-07-06 06:34 UTC
